application:
  host: 0.0.0.0
database:
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: true
email_client:
  # Edit that with your api URL and autorized email
  base_url: "https://api.postmarkapp.com"
  sender_email: "something@gmail.com"
